# Generated by Django 3.2.3 on 2022-01-20 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20220120_1048'),
    ]

    operations = [
        migrations.AlterField(
            model_name='videosub',
            name='url',
            field=models.CharField(max_length=200),
        ),
    ]
